import fs from "node:fs";
import path from "node:path";
import matter from "gray-matter";

const root = process.cwd();
const postsDir = path.join(root, "content", "posts");
const outFile = path.join(root, "src", "generated", "posts.ts");

function jsString(s) {
  return JSON.stringify(String(s ?? ""));
}

function ensureDir(p) {
  fs.mkdirSync(p, { recursive: true });
}

let slugs = [];
if (fs.existsSync(postsDir)) {
  slugs = fs
    .readdirSync(postsDir)
    .filter((f) => f.endsWith(".md"))
    .map((f) => f.replace(/\.md$/, ""))
    .sort();
}

const posts = slugs.map((slug) => {
  const file = path.join(postsDir, `${slug}.md`);
  const raw = fs.readFileSync(file, "utf8");
  const { data, content } = matter(raw);
  return {
    slug,
    title: String(data.title ?? slug),
    description: data.description ? String(data.description) : undefined,
    date: data.date ? String(data.date) : undefined,
    tags: Array.isArray(data.tags) ? data.tags.map(String) : undefined,
    content,
  };
});

ensureDir(path.dirname(outFile));

const header = `// AUTO-GENERATED. DO NOT EDIT.
// Generated by ops/scripts/gen-posts.mjs from content/posts/*.md

export type Post = {
  slug: string;
  title: string;
  description?: string;
  date?: string;
  tags?: string[];
  content: string;
};

export const POSTS: Post[] = [\n`;

const body = posts
  .map((p) => {
    const tags = p.tags ? `[${p.tags.map(jsString).join(", ")}]` : "undefined";
    return `  { slug: ${jsString(p.slug)}, title: ${jsString(p.title)}, description: ${p.description ? jsString(p.description) : "undefined"}, date: ${p.date ? jsString(p.date) : "undefined"}, tags: ${tags}, content: ${jsString(p.content)} },`;
  })
  .join("\n");

const footer = `\n];\n\nexport const POST_SLUGS = POSTS.map(p => p.slug);\nexport const POST_MAP: Record<string, Post> = Object.fromEntries(POSTS.map(p => [p.slug, p]));\n`;

fs.writeFileSync(outFile, header + body + footer, "utf8");
console.log(`[gen-posts] wrote ${outFile} (${posts.length} posts)`);
